Tracker:AddLocations("locations/Docks.json")
Tracker:AddLocations("locations/Downtown.json")
Tracker:AddLocations("locations/Mixes and Trash.json")
Tracker:AddLocations("locations/Northtown.json")
Tracker:AddLocations("locations/Quests.json")
Tracker:AddLocations("locations/Ranks.json")
Tracker:AddLocations("locations/Ray's Realty.json")
Tracker:AddLocations("locations/Suburbia.json")
Tracker:AddLocations("locations/Uptown.json")
Tracker:AddLocations("locations/Westville.json")
Tracker:AddLocations("locations/Overworld.json")
